### ISSUE TITLE
(13) Issue 144: [wireframe only] Post comments and contributions design

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#144]
Currently website has disqus comments widget that is not acceptable as a permanent solution. 

We need a way for people to comment / give feedback to post authors. Our way would be somewhat unconventional:

- We will accept "private feedback" - registered LS users will be able to send a short message to post author that will not be visible to anyone else. 
- We will accept "contributions" - registered LS users will be able to append the post with a valuable piece of information. Post author will be able to "accept", "edit and accept" or "reject" the contribution. 
- We will accept "comments" - no threads, freefeed-like lightweight comments  interface. No line breaks. 

**Private feedback**

**Comment by indeyets** [comment]
plus! 0/7

**Comment by indeyets** [comment]
Attaching related mockups. Ready do discuss the details on Tuesday.

**Comment by xekc** [comment]
plus! 0.6/0.6

**Comment by indeyets** [comment]
Updated wireframes. Changes in this version:

1. Suggest tags UI. Now using simple expanding block instead of floating component (screen "2 - Suggest tags").

2. Post contributions are now published as a special type of comments.

3. Post contributions are now shown in two places:

— As highlighted comments in Comments section.

— As separate blocks in the right panel. Click on a specific block works as an anchor — scrolls to the corresponding comment in Comments section. If the contribution text is too long, in the right panel we show only several lines, and full text is shown in Comments.

4. If a comment / contribution contains a link, it is processed into visual preview.

5. Userpics in comments and contributions are now more compact.

6. In contribution approvement UI the button is now called “Ignore all” instead of “Reject all”.

7. Tags now can be approved one-by-one.
