### ISSUE TITLE
Incorrect date and time displayed in header for all school tags page

### ISSUE THREAD

**Issue by indeyets** [Lokiedu/libertysoil-site#199]
1. Go to News Feed tab
2. Create a post with school tag and Publish it
3. Navigate to this school tag 
 
AR: Standard date and time (March 11, 11:03) displayed in header for all school tags page

See video attachment.

**Comment by xekc** [comment]
@indeyets I assume it's your code - but either way you're likely to be the best person to fix this.

**Comment by Oopscurity** [comment]
The reason is that `school.updated_at` doesn't actually update when the post is published.

**Comment by Oopscurity** [comment]
Most likely, date displayed now is the date of receiving all tags to the database. It can be different for each tag but the difference is in seconds. So date that you see in the school tag page is the same for all tags.

**Comment by Oopscurity** [comment]
plus! 0/2

**Comment by Oopscurity** [comment]
plus! 0.5/0

**Comment by Oopscurity** [comment]
It looks like there are not attepts to change `school.updated_at` anywhere in the API, triggers, reducers and actions that are related to `triggers.createPost`, `client.createPost`, `controller.createPost`, `UPDATE_CREATE_POST_FORM` action, `List` and `CreatePost` components.
I think we should add necessary property to the query there: https://github.com/Lokiedu/libertysoil-site/blob/master/src/api/controller.js#L1032-L1164 - as it done to Post's `updated_at`: https://github.com/Lokiedu/libertysoil-site/blob/master/src/api/controller.js#L1252

And there: https://github.com/Lokiedu/libertysoil-site/blob/master/src/api/controller.js#L1166-L1283 - to provide the opportunity to add new tags to the list of tags already realted to the post. (in order to make `school.update_at` actually update in this case too).

I've found there `schools` only as an array of school names, so we probably need to rewrite the structure of query to get `schools = [{ name: ..., updated_at: ... }]`

**Comment by Oopscurity** [comment]
plus! 1.14/0

**Comment by Oopscurity** [comment]
@dmitryvdovin Probably need your help (read the messages below)

**Comment by Oopscurity** [comment]
plus! 1.68/1.32

**Comment by voidxnull** [comment]
plus! 1/1 Fixed.

**Comment by xekc** [comment]
@dmitryvdovin @indeyets if this is fixed as last comment says and work is done - please move this card to the appropriate location (ready for deploy? deployed?)

**Comment by guiltypet** [comment]
Fixed.
