### ISSUE TITLE
Crash when trying to save post after editing it

### ISSUE THREAD

**Issue by guiltypet** [Lokiedu/libertysoil-site#292]
http://alpha.libertysoil.org/post/edit/ff3fe32f-fd3a-45d7-8f7f-ea2155a42f70
For all devices and browsers

1. Go to News Feed
2. Create new post and publish it
3. Click on pen icon to edit post
4. Try to save it without making any changes

AR: Saving post after editing it causes a crash

For more information please see attached video Recording #57.mp4
Crash log attached: crashlog.txt

**Comment by xekc** [comment]
@ihork can't reproduce it on production. I don't want to see alpha-specific bugs in our lists, it could be a deployment issue. Please re-check, archive if no longer relevant, promote to backlog if it's still actual and @indeyets approves.

In the future please indicate if the issue is occurring both on alpha server and production server - or only on alpha/production. Thanks!

**Comment by guiltypet** [comment]
The issue does not occur anymore. Verified on Windows Pro 7/Chrome 49/FF45/Opera 35, iPad Mini 2/iOS 8.3, iPhone 6 /iOS 9.3.1, Nexus 4/Android 5.1.1
