### ISSUE TITLE
more integration deep tests for  ui 

### ISSUE THREAD

**Issue by RusAlex** [Lokiedu/libertysoil-site#719]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/214144109975508/216649376968759)
┆Created By: Vlad

**Comment by xekc** [comment]
@RusAlex I'm closing this task, because I don't know what it covers. 

I would like you to put some time and try to describe the scope of work here in terms of https://en.wikipedia.org/wiki/INVEST_(mnemonic) - at least somewhat well. Right now it hasn't got anything and looks like "more work here".

Please put some effort into describing this as a distinct block of work that can be linked to a PR or a piece of code that closes the issue. We won't support "placeholder" tasks anymore, sorry. If task is open - it has to be described better to allow cross-check and peer review.

Thank you for understanding.
