### ISSUE TITLE
Small fixes in login/registration

### ISSUE THREAD

**Issue by xekc** [Lokiedu/libertysoil-site#882]
![2017-07-21 19-51-03-y8rt2](https://user-images.githubusercontent.com/1575753/28477815-a7d4359a-6e4d-11e7-88c1-2acb90f12831.png)

- [ ] Languages selector has to be removed for now. 

![2017-07-21 19-54-11-ykljx](https://user-images.githubusercontent.com/1575753/28477933-2abd4ed8-6e4e-11e7-8b38-a192c8d744ef.png)

Narrow mobile responsive behaviour is wrong. On small resolutions there's a fixed 60px background gap line on the left - and stretching data inputs. 

- [ ] Improve layout here:

![2017-07-21 19-58-48-pnsel](https://user-images.githubusercontent.com/1575753/28478082-c8ab3542-6e4e-11e7-846b-563d2cc5afa8.png)

@Oopscurity this can be done better.

- [ ] @voidxnull please describe the code behind green/right ticks to the right of the forms (error reporting / fields validation) for each field. I need to understand how those all work. 

- [ ] @indeyets please evaluate security of new login/registration interface, make other improvement suggestions? We need login-with-redirect (to where you've been before login), we need no-JS login, we need same interface on a separate page too. What do we have, what's missing? Please put a chunk of time and do a review of the whole feature set. Long to-do list for the future would be great to have and the area has a lot of certainty and best practices, standards. How ready is this code (registration through FB etc.) to launch live and expect it to work reliably, in your opinion?

- [ ] Please disconnect intercom:

![2017-07-21 20-05-23-6ms8g](https://user-images.githubusercontent.com/1575753/28478280-ab0dc2ce-6e4f-11e7-81b9-9731d57cd950.png)

from all pages.

**Comment by artkravchenko** [comment]
@indeyets, when are you going to merge #868 and #880?

@vlad,
According to #880, I changed a lot the default way `react-inform` validates fields and reports about the errors for new Sign Up form, so the fields will be validated right after input events and the errors will be reported without requirement to unfocus the field first.
Before #880, we have to unfocus the field at least one time to get the errors visible. That's why there's the bug now when the "green ticks" are shown with incorrectly filled fields on the register form **before they are unfocused at the first time**. Right now the renderer considers the field value as valid if the value is present but the error isn't.

Besides, I implemented the migration to querystring-based `?route=name` interface to use instead of hash-based `#name` (e. g. `?route=login` and `?route=signup`; `https://alpha.libertysoil.org/welcome?route=signup`).

@vlad,
According to #880, I implemented Hebrew and RTL support on the old register form (`/auth#register`) and fixed some visual bugs with new register and login forms; not including this one:
> - [ ] Improve layout here:
